apiVersion: v1
kind: Namespace
metadata:
  name: intone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: intone
  name: shorturl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shorturl
  template:
    metadata:
      labels:
        app: shorturl
        app.kubernetes.io/name: shorturl
        version: "1.01"
    spec:
      containers:
      - name: shorturl
        image: 582822331796.dkr.ecr.us-east-1.amazonaws.com/shorturl:latest
        ports:
        - containerPort: 3200
---
apiVersion: v1
kind: Service
metadata:
  name: shorturl-svc
  namespace: intone
  annotations:
    version: "1.01"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3200
      protocol: TCP
      name: port3200
  selector:
    app.kubernetes.io/name: shorturl
---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: shorturl-ingress
#   namespace: intone
#   annotations:
#     # refer to: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/
#     # https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#load-balancer-name
#     kubernetes.io/ingress.class: alb
#     alb.ingress.kubernetes.io/scheme: internet-facing 
#     alb.ingress.kubernetes.io/target-type: instance
#     alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:582822331796:certificate/b23f3551-dbd6-4b1b-b896-94b774de00bf
#     alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]'
#     # alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
#     alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=600
#     alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=600
#     alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
#     alb.ingress.kubernetes.io/healthcheck-port: traffic-port
#     alb.ingress.kubernetes.io/healthcheck-path: /
#     alb.ingress.kubernetes.io/healthcheck-interval-seconds: '100'
#     alb.ingress.kubernetes.io/load-balancer-name: shorturl-alb
#     # alb.ingress.kubernetes.io/group.name: ingressgroup-cta
#     alb.ingress.kubernetes.io/rewrite-target: "/$1"
#   labels:
#     version: "1.01"
# spec:
#   defaultBackend:
#     service:
#       name: shorturl-svc
#       port:
#         number: 3200